## # Introduction
<p><img src="https://assets.datacamp.com/production/project_981/img/lego_unsplash.jpg" alt="A picture of Lego characters!"></p>
<h3 id="letslookatlegosets">Let's look at Lego sets!</h3>
<p>Lego is a household name across the world, supported by a diverse toy line, hit movies, and a series of successful video games. In this project, we are going to explore a key development in the history of Lego: the introduction of licensed sets such as Star Wars, Super Heroes, and Harry Potter.</p>
<p>It may not be widely known, but Lego has had its share of ups and downs since its inception in the early 20th century. This includes a particularly rough period in the late 90s. As described in <a href="https://www.businessinsider.com/how-lego-made-a-huge-turnaround-2014-2?r=US&IR=T">this article</a>, Lego was only able to survive due to a successful internal brand (Bionicle) and the introduction of its first licensed series: Star Wars. In the instructions panel are the two questions you will need to answer to complete this project.</p>
<p>Before diving into our analysis though, let's become familiar with the two datasets that will help you with this project:<br><br></p>
<div style="background-color: #ebf4f7; color: #595959; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style="font-size:20px"><b>datasets/lego_sets.csv</b></div>
<ul>
    <li><b>set_num:</b> A code that is unique to each set in the dataset. <b><i>This column is critical, and a missing value indicates the set is a duplicate or invalid!</i></b></li>
    <li><b>set_name:</b> A name for every set in the dataset (note that this can be the same for different sets).</li>
    <li><b>year:</b> The date the set was released.</li>
    <li><b>num_parts:</b> The number of parts contained in the set.<b><i> This column is not central to our analyses, so missing values are acceptable.</i></b></li>
        <li><b>theme_name:</b> The name of the sub-theme of the set.</li>
    <li><b>parent_theme:</b> The name of the parent theme the set belongs to. Matches the `name` column of the `parent_themes` csv file.</li>
</ul>

<div style="font-size:20px"><b>datasets/parent_themes.csv</b></div>
<ul>
    <li><b>id:</b> A code that is unique to every theme.</li>
    <li><b>name:</b> The name of the parent theme.</li>
    <li><b>is_licensed:</b> A Boolean column specifying whether the theme is a licensed theme.</li>
</ul>
    </div>
<p>From here on out, it will be your task to explore and manipulate the existing data until you are able to answer the two questions described in the instructions panel. Feel free to add as many cells as necessary. Finally, remember that you are only tested on your answer, not on the methods you use to arrive at the answer!</p>
<p><em><strong>Note:</strong> If you haven't completed a DataCamp project before you should check out the <a href="https://projects.datacamp.com/projects/33">Intro to Projects</a> first to learn about the interface. In this project, you also need to know your way around <code>pandas</code> DataFrames and it's recommended that you take a look at the course <a href="https://www.datacamp.com/courses/data-manipulation-with-pandas">Data Manipulation with pandas</a>.</em></p>

In [146]:
# Use this cell to begin your analyses, and add as many cells as you would like!
import pandas as pd

lego_sets = pd.read_csv('datasets/lego_sets.csv',header=0,parse_dates=['year'])
parent_themes = pd.read_csv('datasets/parent_themes.csv')

In [147]:
print(lego_sets.head())
print(lego_sets.dtypes)

print(parent_themes.head())
print(parent_themes.dtypes)

  set_num                        name       year  num_parts    theme_name  \
0    00-1             Weetabix Castle 1970-01-01      471.0        Castle
1  0011-2           Town Mini-Figures 1978-01-01        NaN  Supplemental
2  0011-3  Castle 2 for 1 Bonus Offer 1987-01-01        NaN  Lion Knights
3  0012-1          Space Mini-Figures 1979-01-01       12.0  Supplemental
4  0013-1          Space Mini-Figures 1979-01-01       12.0  Supplemental

  parent_theme
0     Legoland
1         Town
2       Castle
3        Space
4        Space
set_num                 object
name                    object
year            datetime64[ns]
num_parts              float64
theme_name              object
parent_theme            object
dtype: object
    id     name  is_licensed
0    1  Technic        False
1   22  Creator        False
2   50     Town        False
3  112   Racers        False
4  126    Space        False
id              int64
name           object
is_licensed      bool
dtype: object

In [148]:
lego_sets= lego_sets.dropna(subset=['set_num'])

In [149]:
# Confirm if any other column contains missing value
# In this case it is ok for num_parts.
lego_sets.isnull().any()

set_num         False
name            False
year            False
num_parts        True
theme_name      False
parent_theme    False
dtype: bool

In [150]:
parent_themes.isnull().any()

id             False
name           False
is_licensed    False
dtype: bool

In [151]:
lego = lego_sets.merge(parent_themes,left_on='parent_theme', right_on ='name', how='left')

In [152]:
lego.head()

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,name_y,is_licensed
0,00-1,Weetabix Castle,1970-01-01,471.0,Castle,Legoland,411,Legoland,False
1,0011-2,Town Mini-Figures,1978-01-01,NaN,Supplemental,Town,50,Town,False
2,0011-3,Castle 2 for 1 Bonus Offer,1987-01-01,NaN,Lion Knights,Castle,186,Castle,False
3,0012-1,Space Mini-Figures,1979-01-01,12.0,Supplemental,Space,126,Space,False
4,0013-1,Space Mini-Figures,1979-01-01,12.0,Supplemental,Space,126,Space,False

In [153]:
lego.columns = ['set_num', 'name', 'year','num_parts','theme_name','parent_theme','parent_theme_id', 'parent_theme_','is_licensed']

In [173]:
# test if there is one set_num belonging to multiple parent_theme
test_set_parent =lego[['set_num','parent_theme_id']].drop_duplicates().groupby('set_num').count() 
assert (test_set_parent>1).any()[0] == False

In [155]:
lego_licensed = lego[lego['is_licensed'] ==True]

In [156]:
len(lego_licensed.name.unique())

1086

In [157]:
assert len(lego_licensed) == len(lego_licensed.set_num.unique())

In [158]:
lego_licensed.head()

,set_num,name,year,num_parts,theme_name,parent_theme,parent_theme_id,parent_theme_,is_licensed
44,10018-1,Darth Maul,2001-01-01,1868.0,Star Wars,Star Wars,158,Star Wars,True
45,10019-1,Rebel Blockade Runner - UCS,2001-01-01,NaN,Star Wars Episode 4/5/6,Star Wars,158,Star Wars,True
54,10026-1,Naboo Starfighter - UCS,2002-01-01,NaN,Star Wars Episode 1,Star Wars,158,Star Wars,True
57,10030-1,Imperial Star Destroyer - UCS,2002-01-01,3115.0,Star Wars Episode 4/5/6,Star Wars,158,Star Wars,True
95,10075-1,Spider-Man Action Pack,2002-01-01,25.0,Spider-Man,Super Heroes,482,Super Heroes,True

In [159]:
# Assume only sets with parent theme 'Star Wars' belong to Star War themes.
theme_summary = lego_licensed['parent_theme'].value_counts()
the_force = int(theme_summary['Star Wars']/theme_summary.sum()*100)

In [160]:
type(the_force)

int

In [161]:
count_by_year = lego_licensed.groupby(['year','parent_theme']).set_num.count()

In [162]:
year_groups = count_by_year.groupby(level='year')

In [163]:
year_groups.get_group('2017-01-01').idxmax()

(Timestamp('2017-01-01 00:00:00'), 'Super Heroes')

In [164]:
func = lambda x:  x.idxmax()[1] # extract the second level multi-index

In [165]:
champion_by_year = year_groups.apply(func)

In [166]:
A
new_era = int(champion_by_year[champion_by_year != 'Star Wars'].index.year[0])